apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: todo
    name: dj-dep
spec:
    replicas: 2
    selector:
      matchLabels:
          app: todo
    template:
        metadata:
          labels:
            app: todo
        spec:
          containers:
            - image: dj-img
              imagePullPolicy: Never
              name: todo
              ports:
                - containerPort: 80
              env:
                - name: DB_NAME
                  valueFrom:
                    configMapKeyRef:
                      name: dj-config-map
                      key: psql-db-name

                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: dj-secret
                      key: db-username

                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: dj-secret
                      key: db-password

                - name: DB_HOST
                  valueFrom:
                    configMapKeyRef:
                      name: dj-config-map
                      key: psql-url