apiVersion: v1
kind: Service
metadata:
  name: dj-service
spec:
  type: NodePort
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30333
---
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: todo
    name: dj-depl
spec:
    replicas: 2
    selector:
      matchLabels:
          app: todo
    template:
        metadata:
          labels:
            app: todo
        spec:
          containers:
            - image: djangotodo
              imagePullPolicy: Never
              name: todo
              ports:
                - containerPort: 80
              env:
                - name: DB_NAME
                  value: "todotasks"

                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: dj-secret
                      key: db-username
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: dj-secret
                      key: db-password

                - name: DB_HOST
                  value: psql-service