apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: psql
    name: psql-dep
spec:
    replicas: 1
    selector:
      matchLabels:
          app: psql
    template:
        metadata:
          labels:
            app: psql
        spec:
          containers:
            - image: psql-img
              imagePullPolicy: Never
              name: postgres-container
              ports:
                - containerPort: 5432
              env:
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: dj-secret
                      key: db-password